name: ozipdecryptor

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  PAYLOAD_URL: https://download.c.realme.com/osupdate/RMX2151EU_11_OTA_0880_all_z2qJYj6eZGF0.ozip
  ZIP_NAME: Realme 7
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install git openjdk-8-jdk wget
              sudo apt-get install wget
              sudo apt-get install p7zip-full
              sudo apt-get update -y
              sudo apt-get install -y simg2img  
              sudo apt-get install unzip
              sudo apt-get install zip gzip tar
              sudo apt-get install python3.6-dev libmysqlclient-dev
              sudo apt-get install python3-setuptools
              sudo apt install python-docopt
              sudo apt install python3-docopt
                 
       - name: Decrypting ozip
         run: |
              sudo aria2c http://tdrive.manofuranium.workers.dev/ozipdecrypt.py
              sudo pip install --upgrade setuptools
              sudo pip3 install pycryptodome
              sudo pip3 install docopt
              sudo aria2c $PAYLOAD_URL
              sudo mv *.ozip $ZIP_NAME.ozip
              sudo python ozipdecrypt.py $ZIP_NAME.ozip
              
       - name: Uploading the zip
         run: |
              expect -c "
              spawn sftp ruiii@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"cd /home/pfs/project/rui-ports/dumps\r\"
              set timeout -1
              send \"put $ZIP_NAME.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
